<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net462</TargetFramework>
        <UseWPF>true</UseWPF>
        <RootNamespace>GamesNexus</RootNamespace>
        <AssemblyName>GamesNexus</AssemblyName>
        <OutputType>Library</OutputType>
        <Deterministic>true</Deterministic>
        <DebugType>full</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <WarningLevel>4</WarningLevel>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Resources\Icons\**" />
      <EmbeddedResource Remove="Resources\Icons\**" />
      <None Remove="Resources\Icons\**" />
      <Page Remove="Resources\Icons\**" />
    </ItemGroup>
<ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="PlayniteSDK" Version="6.16.0">
            <PrivateAssets>all</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="System.Net.Http" />
        <Reference Include="System.Drawing" />
        <Reference Include="System.Windows.Forms" />
    </ItemGroup>
    <ItemGroup>
        <None Update="extension.yaml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Properties\Settings.settings">
          <Generator>SettingsSingleFileGenerator</Generator>
          <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
        <None Update="Resources\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Core\Base\" />
    </ItemGroup>
    <ItemGroup>
      <Compile Update="Properties\Settings.Designer.cs">
        <DesignTimeSharedInput>True</DesignTimeSharedInput>
        <AutoGen>True</AutoGen>
        <DependentUpon>Settings.settings</DependentUpon>
      </Compile>
    </ItemGroup>
    <PropertyGroup>
        <PreBuildEvent>powershell -Command "Get-Process Playnite.DesktopApp -ErrorAction SilentlyContinue | Stop-Process -Force; exit 0"
powershell -Command "Get-Process Playnite.DesktopApp -ErrorAction SilentlyContinue | Stop-Process -Force; exit 0"
powershell -Command "Get-Process Playnite.DesktopApp -ErrorAction SilentlyContinue | Stop-Process -Force; exit 0"
</PreBuildEvent>
    </PropertyGroup>
</Project>